### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by revjtanton** [CodeForBaltimore/Bmore-Responsive#96]
### User Story
As a developer
I'd like to have our test coverage be greater than 90%
So that I can be sure our code is safe when adding updates.

### Acceptance Criteria
- [x] CodeCov returns >= 85% coverage

**Comment by carorm** [comment]
I've included testing based off issue #99 so it has at least not gone done in overall coverage. Current branch [carorm/issue_96](https://github.com/CodeForBaltimore/Bmore-Responsive/tree/carorm/issue-96) has an attempt at improving the login process for testing. Will work with another developer to see if I can't jog this one to completion come Friday (4/24). Otherwise will push this back to To-Do.
